# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20171003_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.Device'),
        ),
    ]
