# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20171109_1500'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floorplan',
            unique_together=set([('location', 'floor')]),
        ),
    ]
