# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20171110_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='name',
        ),
    ]
